### ISSUE TITLE
Simulation not loading

### ISSUE THREAD

**Issue by Gaurang-1402** [XuhengChai/UR5-Controller-Python-SDK#1]
Hi,

I followed the instructions and intend to only run the simulation of the robot but don't see it load after running the program. Please suggest a solution.

![image](https://github.com/XuhengChai/UR5-Controller-Python-SDK/assets/71042887/a5296b05-d721-42e0-9ffa-559e1a790b74)

This is the error I get in the terminal

![image](https://github.com/XuhengChai/UR5-Controller-Python-SDK/assets/71042887/76e15351-ef7f-4122-b8d1-ad8e9563608f)

Is it possible to run the simulation without connecting to the real robot?

**Comment by XuhengChai** [comment]
Please refer to the following commands to configure the QmlVTK environment in Anaconda:
        conda create --name QmlVtk python=3.7
        conda activate QmlVtk
        conda install -c conda-forge pyside2=5.13.2 # Linux
        pip install PySide2==5.13.2 # Windows
        pip install vtk==8.1.2 # check compatibility section
